// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://umvfhelmcogikpupglcf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVtdmZoZWxtY29naWtwdXBnbGNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyMzY5OTQsImV4cCI6MjA2NTgxMjk5NH0.v1QFOca6a8nqq-J6eXF17glUbJ7zhoe7jzQhNI92VHA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);